Comments Added
Gauravdarkslayer/ngx-stories pull request #49
Opened 2024-10-04 19:02 UTC by saurabhk9919

Added comments as per instructions

2024-10-05 04:28 UTC, Gauravdarkslayer commented
Hey @saurabhk9919 ,
Can you please self review your code?
Try running locally.
As few html/js comments are visible in DOM view.
Also please avoid over commenting, as most functions are self explanatory.
For eg. You can remove comments such as file imports and basic things.

2024-10-05 04:33 UTC, Gauravdarkslayer requested changes
Add some useful comments to the library itself. 
Projects -> ngx-stories

2024-10-05 04:33 UTC, Gauravdarkslayer commented on src/app/app.component.html
> +-->
Can we please avoid this?

2024-10-05 04:33 UTC, Gauravdarkslayer commented on src/app/app.component.ts
> +// Import necessary modules from Angular and NgxStories library
Please remove this comment.

2024-10-05 04:33 UTC, Gauravdarkslayer commented on src/app/app.component.ts
> +// Define the AppComponent with metadata like selector, template, and style URL
Please remove this comment.

2024-10-05 04:33 UTC, Gauravdarkslayer commented on src/app/app.component.ts
> +  selector: 'app-root', // The component's HTML tag
Please remove this comments(present in @component declaration)

2024-10-05 04:33 UTC, Gauravdarkslayer commented on src/index.html
> +      w[l] = w[l] || []; w[l].push({    //pushing the data to the dataLayer
Please remove this comment.

2024-10-05 04:33 UTC, Gauravdarkslayer commented on src/index.html
> +          new Date().getTime(), event: 'gtm.js' //for the  first script element in the document
Please remove this comment.

2024-10-05 04:33 UTC, Gauravdarkslayer commented on src/index.html
> +      style="display:none;visibility:hidden"></iframe></noscript>  //If the script is not supported by the browser then it will display the message
Please remove this comment.

2024-10-05 04:33 UTC, Gauravdarkslayer commented on src/main.ts
> +// Bootstrapping (initializing) the Angular application with the root component (AppComponent)
Please remove this comment.

2024-10-05 09:57 UTC, saurabhk9919 commented
@Gauravdarkslayer I have made the changes as instructed in the next commit

2024-10-05 11:27 UTC, Gauravdarkslayer commented on projects/ngx-stories/src/lib/ngx-stories.service.ts
> -      // Move to the previous storyGroup if the current story index is 0
Please retain existing comments

2024-10-05 11:42 UTC, Gauravdarkslayer commented on projects/ngx-stories/src/lib/ngx-stories.component.ts
> -      }, 600); // Match the animation duration
Please keep existing comments

2024-10-05 11:42 UTC, Gauravdarkslayer requested changes
Looks like you've removed the existing code comments, please retain them back

2024-10-05 18:17 UTC, saurabhk9919 commented
@Gauravdarkslayer I have retained back the missed out comments

2024-10-06 18:20 UTC, Gauravdarkslayer commented
Can you please check why builds are failing, may be you can try running the project before creating a commit.

2024-10-07 13:52 UTC, saurabhk9919 commented
@Gauravdarkslayer I am unable to solve the build issue but the local run is working properly
![image](https://github.com/user-attachments/assets/72e9ef48-8b54-47b4-8ed2-c5e680826f6d)

2025-04-27 14:15 UTC, Gauravdarkslayer commented
Closing this as it's not relevant any more

2025-04-27 14:15 UTC, closed without merging